<?php

return [
    'entities' => [
        'departments' => [
            'label' => 'Departments',
            'category' => 'Foundation',
            'description' => 'Create the department codes used by courses, teachers, and students.',
            'dependencies' => [],
            'service_method' => 'importDepartments',
            'required_columns' => ['code', 'name'],
            'optional_columns' => ['description'],
            'template_headers' => ['code', 'name', 'description'],
            'template_rows' => [
                ['CS', 'Computer Science', 'Department of Computer Science'],
                ['ENG', 'Engineering', 'Department of Engineering'],
                ['MATH', 'Mathematics', 'Department of Mathematics'],
            ],
            'filename' => 'departments_template.csv',
            'note' => 'Import this first so later files can safely reference department codes.',
        ],

        'semesters' => [
            'label' => 'Semesters',
            'category' => 'Foundation',
            'description' => 'Create the term/semester records used during schedule generation.',
            'dependencies' => [],
            'service_method' => 'importSemesters',
            'required_columns' => ['name', 'code', 'start_date', 'end_date'],
            'optional_columns' => ['academic_year', 'is_active'],
            'template_headers' => ['name', 'code', 'academic_year', 'start_date', 'end_date', 'is_active'],
            'template_rows' => [
                ['Fall 2024', 'F2024', '2024', '2024-09-01', '2024-12-15', '1'],
                ['Spring 2025', 'S2025', '2025', '2025-01-15', '2025-05-31', '1'],
                ['Summer 2025', 'SU2025', '2025', '2025-06-01', '2025-08-31', '0'],
            ],
            'filename' => 'semesters_template.csv',
            'note' => 'Schedule generation is semester-based. academic_year (e.g. 2024) appears on timetables and exports. Re-importing the same code updates the term. Date format: YYYY-MM-DD.',
        ],

        'courses' => [
            'label' => 'Courses',
            'category' => 'Academic Structure',
            'description' => 'Define the course templates, hours per week, level, and room requirements.',
            'dependencies' => ['departments'],
            'service_method' => 'importCourses',
            'required_columns' => ['course_code', 'course_name', 'credits', 'hours_per_week', 'department_code', 'level'],
            'optional_columns' => ['description', 'required_room_type'],
            'template_headers' => ['course_code', 'course_name', 'description', 'credits', 'hours_per_week', 'department_code', 'level', 'required_room_type'],
            'template_rows' => [
                ['CS101', 'Introduction to Programming', 'Learn basic programming concepts', '3', '3', 'CS', '100', 'Lab'],
                ['CS201', 'Data Structures', 'Advanced data structures and algorithms', '3', '4', 'CS', '200', 'Lab'],
                ['MATH101', 'Calculus I', 'Differential and integral calculus', '4', '4', 'MATH', '100', 'Lecture'],
            ],
            'filename' => 'courses_template.csv',
            'note' => 'Department code must match an existing department. hours_per_week affects scheduling. required_room_type: Lab, Lecture, or leave blank.',
        ],

        'course-offerings' => [
            'label' => 'Course Offerings',
            'category' => 'Academic Structure',
            'description' => 'Attach each course to a specific semester before sections are created.',
            'dependencies' => ['courses', 'semesters'],
            'service_method' => 'importCourseOfferings',
            'required_columns' => ['course_code', 'semester_code', 'expected_students'],
            'optional_columns' => [],
            'template_headers' => ['course_code', 'semester_code', 'expected_students'],
            'template_rows' => [
                ['CS101', 'F2024', '120'],
                ['CS201', 'F2024', '80'],
                ['MATH101', 'F2024', '150'],
            ],
            'filename' => 'course_offerings_template.csv',
            'note' => 'Course code and semester code must match existing records. expected_students helps with scheduling.',
        ],

        'sections' => [
            'label' => 'Sections',
            'category' => 'Academic Structure',
            'description' => 'Create the actual class sections that the scheduler will place.',
            'dependencies' => ['course-offerings'],
            'service_method' => 'importSections',
            'required_columns' => ['course_code', 'semester_code', 'section_name', 'capacity'],
            'optional_columns' => [],
            'template_headers' => ['course_code', 'semester_code', 'section_name', 'capacity'],
            'template_rows' => [
                ['CS101', 'F2024', 'Section A', '40'],
                ['CS101', 'F2024', 'Section B', '40'],
                ['CS101', 'F2024', 'Section C', '40'],
                ['CS201', 'F2024', 'Section A', '40'],
            ],
            'filename' => 'sections_template.csv',
            'note' => 'Course and semester must exist. The scheduler will assign these sections to timeslots and rooms.',
        ],

        'teachers' => [
            'label' => 'Teachers',
            'category' => 'Resources & Constraints',
            'description' => 'Create teacher records and login credentials with workload limits.',
            'dependencies' => ['departments'],
            'service_method' => 'importTeachers',
            'required_columns' => ['teacher_id', 'first_name', 'last_name', 'email', 'department_code', 'qualification', 'max_hours_per_week'],
            'optional_columns' => ['phone'],
            'template_headers' => ['teacher_id', 'first_name', 'last_name', 'email', 'department_code', 'qualification', 'max_hours_per_week', 'phone'],
            'template_rows' => [
                ['T001', 'John', 'Smith', 'john.smith@university.edu', 'CS', 'PhD', '20', '555-1001'],
                ['T002', 'Jane', 'Doe', 'jane.doe@university.edu', 'CS', 'M.S.', '18', '555-1002'],
                ['T003', 'Robert', 'Johnson', 'robert.johnson@university.edu', 'MATH', 'PhD', '16', '555-1003'],
            ],
            'filename' => 'teachers_template.csv',
            'note' => 'teacher_id must be unique. Email is used for login credentials. A credentials file will be generated after successful import.',
        ],

        'section-teachers' => [
            'label' => 'Section Teachers',
            'category' => 'Resources & Constraints',
            'description' => 'Assign one or more teachers to each section before generation.',
            'dependencies' => ['sections', 'teachers'],
            'service_method' => 'importSectionTeachers',
            'required_columns' => ['course_code', 'semester_code', 'section_name', 'teacher_code'],
            'optional_columns' => ['append'],
            'template_headers' => ['course_code', 'semester_code', 'section_name', 'teacher_code', 'append'],
            'template_rows' => [
                ['CS101', 'F2024', 'A', 'T001', ''],
                ['CS101', 'F2024', 'A', 'T002', ''],
                ['MATH101', 'F2024', 'B', 'T003', ''],
                ['CS201', 'F2024', 'A', 'T001', ''],
            ],
            'filename' => 'section_teachers_template.csv',
            'note' => 'Use the same course_code, semester_code, and section_name as your Sections import. teacher_code matches teachers.teacher_id (e.g. T001). Multiple teachers for one section: add multiple rows with the same course/semester/section. append=yes keeps existing assignments.',
        ],

        'rooms' => [
            'label' => 'Rooms',
            'category' => 'Resources & Constraints',
            'description' => 'Load available rooms with capacity and type information.',
            'dependencies' => [],
            'service_method' => 'importRooms',
            'required_columns' => ['room_code', 'building', 'floor', 'capacity', 'type'],
            'optional_columns' => ['has_projector', 'has_computers', 'computer_count'],
            'template_headers' => ['room_code', 'building', 'floor', 'capacity', 'type', 'has_projector', 'has_computers', 'computer_count'],
            'template_rows' => [
                ['A101', 'Building A', '1', '40', 'Lecture', '1', '0', '0'],
                ['A102', 'Building A', '1', '30', 'Lab', '1', '1', '30'],
                ['B201', 'Building B', '2', '50', 'Lecture', '1', '0', '0'],
                ['B202', 'Building B', '2', '25', 'Lab', '1', '1', '25'],
            ],
            'filename' => 'rooms_template.csv',
            'note' => 'Capacity must be a number. Type: Lecture or Lab. has_projector/has_computers: 1 (yes) or 0 (no).',
        ],

        'timeslots' => [
            'label' => 'Timeslots',
            'category' => 'Resources & Constraints',
            'description' => 'Define the real timetable slots used by the scheduling engine.',
            'dependencies' => [],
            'service_method' => 'importTimeslots',
            'required_columns' => ['day_of_week', 'start_time', 'end_time', 'slot_code'],
            'optional_columns' => ['student_type', 'time_period'],
            'template_headers' => ['day_of_week', 'start_time', 'end_time', 'slot_code', 'student_type', 'time_period'],
            'template_rows' => [
                ['Monday', '14:00', '15:00', 'REG_MON_1400_1500', 'regular', 'afternoon'],
                ['Monday', '15:00', '16:00', 'REG_MON_1500_1600', 'regular', 'afternoon'],
                ['Monday', '19:30', '20:30', 'REG_MON_1930_2030', 'regular', 'evening'],
                ['Saturday', '14:00', '15:00', 'WKE_SAT_1400_1500', 'weekend', 'afternoon'],
            ],
            'filename' => 'timeslots_template.csv',
            'note' => 'student_type is optional (regular/weekend); leave blank for slots available to all. time_period is optional and for reference only (morning/afternoon/evening). Use 24-hour format. Slot_code must be unique.',
        ],

        'students' => [
            'label' => 'Students',
            'category' => 'Student Demand',
            'description' => 'Create student records, student type, academic cohort (e.g. SE-3A), and login credentials.',
            'dependencies' => ['departments'],
            'service_method' => 'importStudents',
            'required_columns' => ['student_id', 'first_name', 'last_name', 'email', 'department_code', 'academic_section'],
            'optional_columns' => ['student_type', 'phone', 'level', 'enrollment_date'],
            'template_headers' => ['student_id', 'first_name', 'last_name', 'email', 'department_code', 'academic_section', 'student_type', 'phone'],
            'template_rows' => [
                ['S001', 'Alice', 'Brown', 'alice.brown@student.university.edu', 'SE', 'SE-3A', 'regular', '555-2001'],
                ['S002', 'Bob', 'Green', 'bob.green@student.university.edu', 'SE', 'SE-3A', 'regular', '555-2002'],
                ['S003', 'Charlie', 'White', 'charlie.white@student.university.edu', 'SE', 'SE-3B', 'weekend', '555-2003'],
            ],
            'filename' => 'students_template.csv',
            'note' => 'student_type may be regular or weekend. Weekend students are scheduled into weekday evening plus Saturday/Sunday morning/afternoon slots. academic_section is the student cohort (e.g. SE-3A), not a course section.',
        ],

        'student-promotions' => [
            'label' => 'Student Promotions',
            'category' => 'Student Demand',
            'description' => 'Advance existing students to a new year level or cohort without re-importing profiles.',
            'dependencies' => ['students'],
            'service_method' => 'importStudentPromotions',
            'required_columns' => ['student_id'],
            'optional_columns' => ['level', 'academic_section', 'status'],
            'template_headers' => ['student_id', 'level', 'academic_section', 'status'],
            'template_rows' => [
                ['S001', '4', 'SE-4A', 'active'],
                ['S002', '4', 'SE-4A', 'active'],
                ['S003', '4', 'SE-4B', 'active'],
            ],
            'filename' => 'student_promotions_template.csv',
            'note' => 'student_id must already exist. Updates level and/or academic_section only. Then import Enrollments for the new semester — students are not created again.',
        ],

        'enrollments' => [
            'label' => 'Enrollments',
            'category' => 'Student Demand',
            'description' => 'Enroll students in course sections (classes) for scheduling and conflict detection.',
            'dependencies' => ['students', 'sections'],
            'service_method' => 'importEnrollments',
            'required_columns' => ['student_id', 'course_code', 'semester_code', 'section_name'],
            'optional_columns' => ['section_code', 'academic_section', 'enrolled_at'],
            'template_headers' => ['student_id', 'course_code', 'semester_code', 'section_name', 'academic_section'],
            'template_rows' => [
                ['S001', 'CS101', 'F2024', 'A', ''],
                ['S001', 'CS201', 'F2024', 'A', ''],
                ['S002', 'CS101', 'F2024', 'B', ''],
                ['', 'CS101', 'F2024', 'A', 'SE-3A'],
            ],
            'filename' => 'enrollments_template.csv',
            'note' => 'Links students to course sections (not academic_section). Use course_code + semester_code + section_name, or section_code (CS101_F2024_A). Leave student_id blank and set academic_section to enroll an entire cohort (e.g. SE-3A).',
        ],
    ],
];
