<?php

return [
    'entities' => [
        'departments' => [
            'label' => 'Departments',
            'category' => 'Foundation',
            'description' => 'Create the department codes used by courses, teachers, and students.',
            'dependencies' => [],
            'required_columns' => ['code', 'name'],
            'optional_columns' => ['description'],
            'template_headers' => ['code', 'name', 'description'],
            'template_rows' => [
                ['CS', 'Computer Science', 'Department of Computer Science'],
                ['ENG', 'Engineering', 'Department of Engineering'],
                ['MATH', 'Mathematics', 'Department of Mathematics'],
            ],
            'filename' => 'departments_template.csv',
            'note' => 'Import this first so later files can safely reference department codes.',
        ],

        'semesters' => [
            'label' => 'Semesters',
            'category' => 'Foundation',
            'description' => 'Create the term/semester records used during schedule generation.',
            'dependencies' => [],
            'required_columns' => ['name', 'code', 'start_date', 'end_date'],
            'optional_columns' => ['is_active'],
            'template_headers' => ['name', 'code', 'start_date', 'end_date', 'is_active'],
            'template_rows' => [
                ['Fall 2024', 'F2024', '2024-09-01', '2024-12-15', '1'],
                ['Spring 2025', 'S2025', '2025-01-15', '2025-05-31', '1'],
                ['Summer 2025', 'SU2025', '2025-06-01', '2025-08-31', '0'],
            ],
            'filename' => 'semesters_template.csv',
            'note' => 'Schedule generation is semester-based. Date format: YYYY-MM-DD. is_active: 1 or 0 (1 = active, 0 = inactive).',
        ],

        'courses' => [
            'label' => 'Courses',
            'category' => 'Academic Structure',
            'description' => 'Define the course templates, hours per week, level, and room requirements.',
            'dependencies' => ['departments'],
            'required_columns' => ['course_code', 'course_name', 'credits', 'hours_per_week', 'department_code', 'level'],
            'optional_columns' => ['description', 'required_room_type'],
            'template_headers' => ['course_code', 'course_name', 'description', 'credits', 'hours_per_week', 'department_code', 'level', 'required_room_type'],
            'template_rows' => [
                ['CS101', 'Introduction to Programming', 'Learn basic programming concepts', '3', '3', 'CS', '100', 'Lab'],
                ['CS201', 'Data Structures', 'Advanced data structures and algorithms', '3', '4', 'CS', '200', 'Lab'],
                ['MATH101', 'Calculus I', 'Differential and integral calculus', '4', '4', 'MATH', '100', 'Lecture'],
            ],
            'filename' => 'courses_template.csv',
            'note' => 'Department code must match an existing department. hours_per_week affects scheduling. required_room_type: Lab, Lecture, or leave blank.',
        ],

        'course-offerings' => [
            'label' => 'Course Offerings',
            'category' => 'Academic Structure',
            'description' => 'Attach each course to a specific semester before sections are created.',
            'dependencies' => ['courses', 'semesters'],
            'required_columns' => ['course_code', 'semester_code', 'expected_students'],
            'optional_columns' => [],
            'template_headers' => ['course_code', 'semester_code', 'expected_students'],
            'template_rows' => [
                ['CS101', 'F2024', '120'],
                ['CS201', 'F2024', '80'],
                ['MATH101', 'F2024', '150'],
            ],
            'filename' => 'course_offerings_template.csv',
            'note' => 'Course code and semester code must match existing records. expected_students helps with scheduling.',
        ],

        'sections' => [
            'label' => 'Sections',
            'category' => 'Academic Structure',
            'description' => 'Create the actual class sections that the scheduler will place.',
            'dependencies' => ['course-offerings'],
            'required_columns' => ['course_code', 'semester_code', 'section_name', 'capacity'],
            'optional_columns' => [],
            'template_headers' => ['course_code', 'semester_code', 'section_name', 'capacity'],
            'template_rows' => [
                ['CS101', 'F2024', 'Section A', '40'],
                ['CS101', 'F2024', 'Section B', '40'],
                ['CS101', 'F2024', 'Section C', '40'],
                ['CS201', 'F2024', 'Section A', '40'],
            ],
            'filename' => 'sections_template.csv',
            'note' => 'Course and semester must exist. The scheduler will assign these sections to timeslots and rooms.',
        ],

        'teachers' => [
            'label' => 'Teachers',
            'category' => 'Resources & Constraints',
            'description' => 'Create teacher records and login credentials with workload limits.',
            'dependencies' => ['departments'],
            'required_columns' => ['teacher_id', 'first_name', 'last_name', 'email', 'department_code', 'qualification', 'max_hours_per_week'],
            'optional_columns' => ['phone'],
            'template_headers' => ['teacher_id', 'first_name', 'last_name', 'email', 'department_code', 'qualification', 'max_hours_per_week', 'phone'],
            'template_rows' => [
                ['T001', 'John', 'Smith', 'john.smith@university.edu', 'CS', 'PhD', '20', '555-1001'],
                ['T002', 'Jane', 'Doe', 'jane.doe@university.edu', 'CS', 'M.S.', '18', '555-1002'],
                ['T003', 'Robert', 'Johnson', 'robert.johnson@university.edu', 'MATH', 'PhD', '16', '555-1003'],
            ],
            'filename' => 'teachers_template.csv',
            'note' => 'teacher_id must be unique. Email is used for login credentials. A credentials file will be generated after successful import.',
        ],

        'section-teachers' => [
            'label' => 'Section Teachers',
            'category' => 'Resources & Constraints',
            'description' => 'Assign one or more teachers to each section before generation.',
            'dependencies' => ['sections', 'teachers'],
            'required_columns' => ['section_code', 'teacher_id'],
            'optional_columns' => [],
            'template_headers' => ['section_code', 'teacher_id'],
            'template_rows' => [
                ['CS101_F2024_A', 'T001'],
                ['CS101_F2024_B', 'T002'],
                ['CS101_F2024_C', 'T001'],
                ['CS201_F2024_A', 'T001'],
                ['MATH101_F2024_A', 'T003'],
            ],
            'filename' => 'section_teachers_template.csv',
            'note' => 'Every section must have at least one teacher. If multiple teachers per section, use multiple rows with same section_code.',
        ],

        'rooms' => [
            'label' => 'Rooms',
            'category' => 'Resources & Constraints',
            'description' => 'Load available rooms with capacity and type information.',
            'dependencies' => [],
            'required_columns' => ['room_code', 'building', 'floor', 'capacity', 'type'],
            'optional_columns' => ['has_projector', 'has_computers', 'computer_count'],
            'template_headers' => ['room_code', 'building', 'floor', 'capacity', 'type', 'has_projector', 'has_computers', 'computer_count'],
            'template_rows' => [
                ['A101', 'Building A', '1', '40', 'Lecture', '1', '0', '0'],
                ['A102', 'Building A', '1', '30', 'Lab', '1', '1', '30'],
                ['B201', 'Building B', '2', '50', 'Lecture', '1', '0', '0'],
                ['B202', 'Building B', '2', '25', 'Lab', '1', '1', '25'],
            ],
            'filename' => 'rooms_template.csv',
            'note' => 'Capacity must be a number. Type: Lecture or Lab. has_projector/has_computers: 1 (yes) or 0 (no).',
        ],

        'timeslots' => [
            'label' => 'Timeslots',
            'category' => 'Resources & Constraints',
            'description' => 'Define the real timetable slots used by the scheduling engine.',
            'dependencies' => [],
            'required_columns' => ['day_of_week', 'start_time', 'end_time', 'slot_code'],
            'optional_columns' => [],
            'template_headers' => ['day_of_week', 'start_time', 'end_time', 'slot_code'],
            'template_rows' => [
                ['Monday', '08:00', '09:30', 'MON_0800'],
                ['Monday', '09:45', '11:15', 'MON_0945'],
                ['Monday', '11:30', '13:00', 'MON_1130'],
                ['Monday', '14:00', '15:30', 'MON_1400'],
                ['Tuesday', '08:00', '09:30', 'TUE_0800'],
                ['Tuesday', '09:45', '11:15', 'TUE_0945'],
                ['Wednesday', '08:00', '09:30', 'WED_0800'],
                ['Thursday', '08:00', '09:30', 'THU_0800'],
                ['Friday', '08:00', '09:30', 'FRI_0800'],
            ],
            'filename' => 'timeslots_template.csv',
            'note' => 'Time format: HH:MM (24-hour). Day of week: Monday, Tuesday, Wednesday, Thursday, Friday. slot_code must be unique.',
        ],

        'students' => [
            'label' => 'Students',
            'category' => 'Users & Enrollment',
            'description' => 'Create student records and login credentials.',
            'dependencies' => ['departments'],
            'required_columns' => ['student_id', 'first_name', 'last_name', 'email', 'department_code'],
            'optional_columns' => ['phone', 'date_of_birth'],
            'template_headers' => ['student_id', 'first_name', 'last_name', 'email', 'department_code', 'phone', 'date_of_birth'],
            'template_rows' => [
                ['S001', 'Alice', 'Brown', 'alice.brown@student.university.edu', 'CS', '555-2001', '2003-05-15'],
                ['S002', 'Bob', 'Green', 'bob.green@student.university.edu', 'CS', '555-2002', '2003-08-22'],
                ['S003', 'Charlie', 'White', 'charlie.white@student.university.edu', 'MATH', '555-2003', '2004-01-10'],
            ],
            'filename' => 'students_template.csv',
            'note' => 'student_id must be unique. Email is used for login credentials. Date format: YYYY-MM-DD.',
        ],

        'enrollments' => [
            'label' => 'Enrollments',
            'category' => 'Users & Enrollment',
            'description' => 'Enroll students in course sections.',
            'dependencies' => ['students', 'sections'],
            'required_columns' => ['student_id', 'section_code'],
            'optional_columns' => [],
            'template_headers' => ['student_id', 'section_code'],
            'template_rows' => [
                ['S001', 'CS101_F2024_A'],
                ['S002', 'CS101_F2024_B'],
                ['S003', 'MATH101_F2024_A'],
                ['S001', 'CS201_F2024_A'],
            ],
            'filename' => 'enrollments_template.csv',
            'note' => 'student_id and section_code must match existing records. One enrollment per row.',
        ],
    ],
];
